# data creation

```{r}
library(overseer)
library(mrgsolve)
# library(PKPDmisc)
library(tidyverse)
library(rstan)
```

```{r}
models <- source("../models/models.R")$value
mod_list <- set_names(map(models$available(), ~models$use(.x)) , models$available())
```

```{r}
see(mod_list$inf_wt)
```

```{r}
id_data <- data_frame(
  ID = 1:50,
  time = 0,
  amt = 1000,
  ii = 12,
  addl = 8,
  dose = amt,
  cmt = 1,
  evid = 1, 
  rate = -2
) %>%
  mutate(WT = round(runif(n(), 40, 100), 1))
```


```{r }
sim_output <- mod_list$inf_wt %>% 
  data_set(id_data) %>%
  mrgsim(end = 12*8 + 12)

sim_output
```

```{r}
sim_data <- sim_output %>% 
  as_data_frame() 

sim_data %>%
  ggplot(aes(x = time, y = CP, group = ID, color = WT)) + 
  geom_line() +
  geom_point()
```

```{r}
obs_times <- 0:9 %>% map(~.x*12 +c(0, 1, 3, 8)) %>% unlist %>%
  unique
obs_times <- obs_times[order(obs_times)]
```

```{r}
output_data <- sim_data %>% 
  filter(time %in% obs_times)
```


```{r}
output_data %>%
  split(.$ID) %>% 
  map(function(.x){
    .x %>%
      ggplot(aes(x = time, y = CP, group = ID)) +
      geom_line() +
      geom_point(aes(x = DV)) + 
      facet_wrap(~ID)
  })
```

```{r}
devtools::session_info()
```

```{r}
for_stan <- output_data %>%
  distinct(ID, time, .keep_all = TRUE) %>%
  select(ID, time, DV, WT) %>%
  left_join(id_data %>% select(-dose)) %>%
  replace_na(list(amt = 0, ii = 0, addl = 0, cmt = 2, evid = 0)) %>%
  mutate(rate = amt) %>%
mutate(
  DV = round(DV, 2),
  rate = amt,
  ss= 0
)

single_obs <- for_stan %>%
  summarise(
    nt = n(),
    nSubjects = n_distinct(ID),
    nObs = sum(ifelse(evid == 0, 1, 0))
  )

single_obs %>% as.list()

first_last <- for_stan %>%
  mutate(index = row_number()) %>%
  group_by(ID) %>%
  summarize(first = first(index),
            last = last(index)) %>%
  select(-ID) %>% as.list

df_data <- for_stan %>% as.list

Obs <- for_stan %>%
  mutate(index = row_number()) %>%
  filter(evid == 0) %>%
  select(iObs = index, cObs = DV) %>% as.list


data <- c(single_obs, first_last, df_data, Obs)
data$cmt[1] <- 2  # in Torsten, the first compartment is the gut.
                  # The central compartment will the be the second one.
with(data, stan_rdump(ls(data), file = "stan_data.R"))

# save the file in the model directory
modelName <- "oneCptPop"
projectDir <- dirname(getwd())
with(data, stan_rdump(ls(data), file = file.path(projectDir, "stanModel", paste0(modelName, ".data.R"))))

```
